# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code for Boulder
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The official homepage for the Boulder Brigade of Code for America
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.codeforboulder.com" # the base hostname & protocol for your site
twitter_username: CodeforBoulder
github_username: CodeForBoulder

# Build settings
markdown: kramdown
